# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YSTransitionPod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YSTransitionPod

pod 'YYKit', '~> 1.0.9‘
  target 'YSTransitionPodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YSTransitionPodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
